variables:
  EXCLUDE: "--exclude-glob .git* --exclude '.git/' --exclude './files --exclude './Readme.md'"
  SOURCE_DIR: "./"
  GIT_SUBMODULE_STRATEGY: recursive

  # STAGING
  DEST_DIR: "/"
  HOST_STAGING: "ftp://rootomat.de/"
  USERNAME_STAGING: "manuelftp5"
  PASSWORD_STAGING: "asofxpqweg"


deploy_master:
  stage: deploy
  script: 
  - echo "Deploying"  
  - lftp -c "set ssl:verify-certificate no;open -u $USERNAME_STAGING,$PASSWORD_STAGING $HOST_STAGING; mirror -Rv --ignore-time --parallel=10 $EXCLUDE $SOURCE_DIR $DEST_DIR_STAGING"
  environment:
    name: production
    url: https://rootomat.de/
  when: manual
  only:
  - master
